name: xsensor workflow
on:
  pull_request:
    branches:
      - master
jobs:
  PR-CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: pip3 install virtualenv
      - run: python3 --version
      - run: python3 -m virtualenv .venv -p 3.6
      - run: source .venv\bin\activate
      - run: pip install -r requirements.txt
      - run: python -m coverage run -m unittest discover sample --fail-under 95
      - run: python -m pylint --fail-under 10 sample
      - run: deactivate
      - run: rm -rf .venv